# Generated by Django 2.1 on 2021-03-11 16:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210310_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gcash_number',
            field=models.IntegerField(default='+63', unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/round.png', help_text='Help us recognize you. ;)', upload_to=user.models.Profile.dp_directory_path, verbose_name='Profile Picture: '),
        ),
    ]
